### ISSUE TITLE
Another missing verification mail

### ISSUE THREAD

**Issue by GeroHerkenrath** [CocoaPods/cocoapods-trunk#102]
For some reason my previous authentication token was reported as invalid when I tried to publish a new version for my pod "Trustbadge". I haven't pushed a new version of my pod in a while and upgraded to Macos High Sierra in the meantime. CocoaPods was also updated in the meantime.

I tried `pod trunk register gero.herkenrath@trustedshops.de 'Gero Herkenrath' --description='Macbook' --verbose`, but did not receive a verification mail. 

Is it possible that this is due to a previous session preventing it or something? If so, can this be fixed somehow? Or is my mail on a spam filter all of a sudden?

If it is something I can do, please let me know, if not, I'd appreciate a fix (even if just temporary) so I can publish my release. Thanks in advance.

**Comment by orta** [comment]
That email isn't showing up on trunk as being blocked/bounced or spam - it's showing as delivered

<img width="1270" alt="screen shot 2017-11-22 at 9 42 12 am" src="https://user-images.githubusercontent.com/49038/33133031-7387b9c4-cf69-11e7-88c2-8f0fdf2bfbcd.png">

**Comment by GeroHerkenrath** [comment]
Thanks a LOT for the quick reply. Obviously I checked my spam folder already, but now something tells me our infrastructure here messes up (i.e. I don't trust our exchange server & spam filter service...). I will close this for now. Thanks again.
