### ISSUE TITLE
Can't receive authentication email

### ISSUE THREAD

**Issue by Jauzee** [CocoaPods/cocoapods-trunk#103]
I know there are another similar issue, but need to create this one to draw your attention.

My email: jauzee@ramotion.com — it's Gmail enterprise account. Requested several times, but no success. 

@orta can you please check what's wrong here?

**Comment by orta** [comment]
We have a block on it because your account was disabled when trunk first sent out an email:
<img width="911" alt="screen shot 2017-11-29 at 8 18 51 am" src="https://user-images.githubusercontent.com/49038/33377044-0598eeea-d4de-11e7-8e8b-f943490f38bc.png">

I've removed the block

**Comment by Jauzee** [comment]
Thank you @orta!
