### ISSUE TITLE
Rename and existing Pod

### ISSUE THREAD

**Issue by Ethenyl** [CocoaPods/cocoapods-trunk#105]
Hi,

I'm the owner of `JamfKit` (formerly uploaded in the master repo as `JAMFKit`).

I had to rename my repository and now I'm completely unable to upload a new version of my library since the name is case insensitive.

It seems that the `trunk` command is missing a `rename` feature to rename a full Pod.

Maybe someone have a better solution.

Thanks for your help.

**Comment by segiddins** [comment]
There is no renaming of Pods, you always have to push an entirely new pod (and then can deprecate the original in favor of the new one).

**Comment by Ethenyl** [comment]
Hi @segiddins,

Thanks for the answer, I tried this method and in fact, the old pod was removed, but the empty folder with the name `JAMFKit ` is still in place, preventing me to create a new **Pod** with the name `JamfKit`.

At least, the `delete` command should remove empty folder in case there was only a single version.

Do you see the issue I'm facing?

**Comment by orta** [comment]
I'm afraid they have the same identifier if they are different capitalization - because they are represented on a file system and filesystems can be case-insensitive.

**Comment by orta** [comment]
Realistically, to re-name a pod there'd need to be an API on trunk.cocoapods and a command in the CLI

**Comment by Ethenyl** [comment]
Thanks @orta for the feedback, so... if I understand correctly, there's nothing I can do about it and I'll have to continue to push with `JAMFKit` instead? 😢

**Comment by orta** [comment]
There's nothing you can do unless you want to ship some code, realistically
