### ISSUE TITLE
Email verification not sen't

### ISSUE THREAD

**Issue by felixsolorzano** [CocoaPods/cocoapods-trunk#106]
I'm trying to register my email but didn't receive any email when running:

```
pod trunk register jonathan@elaniin.com 'Jonathan Solorzano' --description='Jonathan's Macbook Pro'
```
Our email hosting is Google... so Idk what I'm doing wrong

@orta help please.

**Comment by orta** [comment]
I can't find any emails sent, or any of the usual bounce/spams/anything - are you seeing error messages?

**Comment by felixsolorzano** [comment]
I'm sorry, it was a problem with a closing string `'` at Jonathan's MacBook Pro, sorry
