### ISSUE TITLE
appsight.io integration

### ISSUE THREAD

**Issue by Juriv** [CocoaPods/cocoapods-trunk#107]
Hey, I wondering if there anything I need to do in order to track which apps consume my pod? 
We have plenty of pods and showroom app on the appstore which shows how our libs work, however Neither libs nor app data could be found on appsight.io

**Comment by orta** [comment]
Nothing from the CocoaPods side I'm afraid, we send along the pod unique ID and it's on their side to figure out what to show. Would recommend asking them
