### ISSUE TITLE
missing verification mail

### ISSUE THREAD

**Issue by akhilcb** [CocoaPods/cocoapods-trunk#108]
We tried to do pod trunk register with mail id "cocoapods@bluejeans.com" but did not receive a verification mail. Our IT has enabled getting mails from external mails to this now. @orta  Could you please unblock from your side so that I can try again. I tried again but didn't get any mail.

**Comment by orta** [comment]
OK, that's it unblocked

**Comment by akhilcb** [comment]
Thanks a lot. It worked.
