### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by hsoehalim** [CocoaPods/cocoapods-trunk#110]
Hi There,

I've ran this several times: pod trunk register harry@answerdash.com 'Harry Soehalim'
and I haven't received any emails so far. I've filed an issue under https://github.com/CocoaPods/CocoaPods/issues/7852 and told to file it here instead. Can you help?

Thanks,
Harry

**Comment by segiddins** [comment]
Looks like the email bounced, try again?

**Comment by hsoehalim** [comment]
Thank you! It's working now :)

**Comment by kranjanford** [comment]
i am getting same issue.

/Users/kranjan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'cocoapods-trunk' (< 2.0, >= 1.3.1) - did find: [cocoapods-trunk-1.3.0] (Gem::MissingSpecVersionError)
