### ISSUE TITLE
pod trunk delete podName podVersion not work

### ISSUE THREAD

**Issue by SunnySunning** [CocoaPods/cocoapods-trunk#113]
I use the '`pod trunk delete WebViewPool 0.1.0`',its work fine,show me its excute success! but after a while, the WebViewPool 0.1.0 **reappear** in the cocoapods index repo,its very distress! whats wrong with the cocoapods index repo,help me!

**Comment by SunnySunning** [comment]
> It was deleted [CocoaPods/Specs@08d3de9](https://github.com/CocoaPods/Specs/commit/08d3de9a7ab)

But it was still in,its link:[https://github.com/CocoaPods/Specs/blob/41b5a61d24d68aecc42e1066958d99de9c8d59e8/Specs/6/5/6/WebViewPool/0.1.0/WebViewPool.podspec.json](url)

**Comment by SunnySunning** [comment]
> > It was deleted [CocoaPods/Specs@08d3de9](https://github.com/CocoaPods/Specs/commit/08d3de9a7ab)
> 
> But it was still in,its link:[https://github.com/CocoaPods/Specs/blob/41b5a61d24d68aecc42e1066958d99de9c8d59e8/Specs/6/5/6/WebViewPool/0.1.0/WebViewPool.podspec.json](url)
**WARNNING**: If you click the url cannot open it, you can copy and then paste in the browser input field！

**Comment by amorde** [comment]
@SunnySunning that link is viewing a specific point in the repository history, at which the podspec still existed.

Here is the containing folder of your podspec on master: https://github.com/CocoaPods/Specs/tree/master/Specs/6/5/6

Deleting a podspec does not erase it from the repo history

**Comment by amorde** [comment]
We will not rewrite the history of the repo to delete a single spec, sorry. There also isn't anything in that Podspec that appears to be a security issue at first glance (ex. API keys)

I'm going to close this but we can continue discussion here if you have additional questions

**Comment by dnkoutso** [comment]
Agreed
