### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by Tulleb** [CocoaPods/cocoapods-trunk#114]
Hey team, thanks for your work.

I don't receive any email from pod trunk register guillaume@bellut.com 'Guillaume Bellut'. Am I in a blacklist or anything?

**Comment by orta** [comment]
We have it marked as delivered by your mail server:

<img width="1206" alt="screen shot 2018-10-01 at 7 53 53 am" src="https://user-images.githubusercontent.com/49038/46287012-2e057d00-c54f-11e8-83ae-5398616eccd7.png">

Spam folder?

**Comment by Tulleb** [comment]
No nothing in my spams... I'm trying again right now.

**Comment by Tulleb** [comment]
Received this time :)
