### ISSUE TITLE
An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

### ISSUE THREAD

**Issue by LucasVanDongen** [CocoaPods/cocoapods-trunk#115]
I'm trying to update my library in the same way I have been doing in the last weeks. Pushing a version tag, matching the version tag in .podspec and then calling `pod trunk push`. It looks a lot like https://github.com/CocoaPods/cocoapods-trunk/issues/59

```opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.5.3\r\nAuthorization: Token ed3f530c4b3056117c1f4c2aef127848\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 753\r\n\r\n"
<- "{\"name\":\"Constraint\",\"version\":\"0.9.3\",\"summary\":\"Constraint is a simple Swift wrapper for iOS Auto Layout that has a very natural syntax.\",\"description\":\"Constraint is a simple Swift wrapper for iOS Auto Layout that has a very natural syntax. You can either create layouts directly using the `Constraint` class methods or use the extensions on `UIView` related classes.\",\"homepage\":\"https://github.com/lucasvandongen/Constraint\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"authors\":{\"lucasvandongen\":\"lucas.van.dongen@gmail.com\"},\"source\":{\"git\":\"https://github.com/lucasvandongen/Constraint.git\",\"tag\":\"0.9.3\"},\"swift_version\":\"4.2\",\"social_media_url\":\"https://twitter.com/LucasVanDongen\",\"platforms\":{\"ios\":\"9.0\"},\"source_files\":\"Classes/**/*.swift\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 18 Oct 2018 13:15:35 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:70:in `print_error'
/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:30:in `request_url'
/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:36:in `request_path'
/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:83:in `push_to_trunk'
/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:69:in `run'
/Users/lucas/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/lucas/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/lucas/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/lucas/.rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
/Users/lucas/.rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
/Users/lucas/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/lucas/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

This is the pod spec:
```
Pod::Spec.new do |s|
  s.name             = 'Constraint'
  s.version          = '0.9.3'
  s.summary          = 'Constraint is a simple Swift wrapper for iOS Auto Layout that has a very natural syntax.'

  s.description      = <<-DESC
Constraint is a simple Swift wrapper for iOS Auto Layout that has a very natural syntax. You can either create layouts directly using the `Constraint` class methods or use the extensions on `UIView` related classes.
                       DESC

  s.homepage         = 'https://github.com/lucasvandongen/Constraint'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'lucasvandongen' => '##redacted##' }
  s.source           = { :git => 'https://github.com/lucasvandongen/Constraint.git', :tag => s.version.to_s }
  s.swift_version = '4.2'
  s.social_media_url = 'https://twitter.com/LucasVanDongen'

  s.platform = :ios, '9.0'

  s.source_files = 'Classes/**/*.swift'
end
```

Version 0.9.3 fixes a bug in 0.9.1 where alignments of the layout would be swapped sometimes, which is pretty important for a layout cocoapod.

**Comment by LucasVanDongen** [comment]
It just worked

**Comment by dnkoutso** [comment]
Might be an intermittent issue. We will keep monitoring but for now I am closing.

**Comment by jigs611989** [comment]
@dnkoutso I see this error.

$ pod trunk register jigs.patelit@gmail.com 'Jignesh Patel' --description='Personal Laptop' --verbose
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.8.4\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 89\r\n\r\n"
<- "{\"email\":\"jigs.patelit@gmail.com\",\"name\":\"Jignesh Patel\",\"description\":\"Personal Laptop\"}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Sun, 17 May 2020 12:16:15 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:70:in `print_error'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:30:in `request_url'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:36:in `request_path'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/register.rb:61:in `run'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `load'
/Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `<main>'

**Comment by Adelais0** [comment]
> @dnkoutso I see this error.
> 
> $ pod trunk register [jigs.patelit@gmail.com](mailto:jigs.patelit@gmail.com) 'Jignesh Patel' --description='Personal Laptop' --verbose
> opening connection to trunk.cocoapods.org:443...
> opened
> starting SSL for trunk.cocoapods.org:443...
> SSL established
> <- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.8.4\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 89\r\n\r\n"
> <- "{"email":"[jigs.patelit@gmail.com](mailto:jigs.patelit@gmail.com)","name":"Jignesh Patel","description":"Personal Laptop"}"
> -> "HTTP/1.1 500 Internal Server Error\r\n"
> -> "Date: Sun, 17 May 2020 12:16:15 GMT\r\n"
> -> "Connection: keep-alive\r\n"
> -> "Strict-Transport-Security: max-age=31536000\r\n"
> -> "Content-Type: application/json\r\n"
> -> "Content-Length: 141\r\n"
> -> "X-Content-Type-Options: nosniff\r\n"
> -> "Server: thin 1.6.2 codename Doc Brown\r\n"
> -> "Via: 1.1 vegur\r\n"
> -> "\r\n"
> reading 141 bytes...
> -> "{"error":"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."}"
> read 141 bytes
> Conn keep-alive
> [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
> 
> /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:70:in `print_error' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:30:in `request_url'
> /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:36:in `request_path' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/register.rb:61:in `run'
> /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
> /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>' /Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `load'
> /Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `
> 
> '

same here.

**Comment by Romixery** [comment]
Same here:

> pod trunk register topcoder.romixery@gmail.com "Macbook Pro" --verbose
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.9.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 79\r\n\r\n"
<- "{\"email\":\"topcoder.romixery@gmail.com\",\"name\":\"Macbook Pro\",\"description\":null}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Mon, 18 May 2020 11:45:24 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

> /Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:70:in `print_error'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:30:in `request_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/register.rb:61:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by liuyongjiesail** [comment]
> Same here:
> 
> > pod trunk register [topcoder.romixery@gmail.com](mailto:topcoder.romixery@gmail.com) "Macbook Pro" --verbose
> > opening connection to trunk.cocoapods.org:443...
> > opened
> > starting SSL for trunk.cocoapods.org:443...
> > SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
> > <- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.9.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 79\r\n\r\n"
> > <- "{"email":"[topcoder.romixery@gmail.com](mailto:topcoder.romixery@gmail.com)","name":"Macbook Pro","description":null}"
> > -> "HTTP/1.1 500 Internal Server Error\r\n"
> > -> "Date: Mon, 18 May 2020 11:45:24 GMT\r\n"
> > -> "Connection: keep-alive\r\n"
> > -> "Strict-Transport-Security: max-age=31536000\r\n"
> > -> "Content-Type: application/json\r\n"
> > -> "Content-Length: 141\r\n"
> > -> "X-Content-Type-Options: nosniff\r\n"
> > -> "Server: thin 1.6.2 codename Doc Brown\r\n"
> > -> "Via: 1.1 vegur\r\n"
> > -> "\r\n"
> > reading 141 bytes...
> > -> "{"error":"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."}"
> > read 141 bytes
> > Conn keep-alive
> > [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
> 
> > /Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:70:in `print_error' /Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:30:in `request_url'
> > /Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:36:in `request_path' /Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/register.rb:61:in `run'
> > /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
> > /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>' /usr/local/bin/pod:23:in `load'
> > /usr/local/bin/pod:23:in `'

Hello, is this error resolved? Hope to inform the solution

**Comment by liuyongjiesail** [comment]
> > @dnkoutso I see this error.
> > $ pod trunk register [jigs.patelit@gmail.com](mailto:jigs.patelit@gmail.com) 'Jignesh Patel' --description='Personal Laptop' --verbose
> > opening connection to trunk.cocoapods.org:443...
> > opened
> > starting SSL for trunk.cocoapods.org:443...
> > SSL established
> > <- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.8.4\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 89\r\n\r\n"
> > <- "{"email":"[jigs.patelit@gmail.com](mailto:jigs.patelit@gmail.com)","name":"Jignesh Patel","description":"Personal Laptop"}"
> > -> "HTTP/1.1 500 Internal Server Error\r\n"
> > -> "Date: Sun, 17 May 2020 12:16:15 GMT\r\n"
> > -> "Connection: keep-alive\r\n"
> > -> "Strict-Transport-Security: max-age=31536000\r\n"
> > -> "Content-Type: application/json\r\n"
> > -> "Content-Length: 141\r\n"
> > -> "X-Content-Type-Options: nosniff\r\n"
> > -> "Server: thin 1.6.2 codename Doc Brown\r\n"
> > -> "Via: 1.1 vegur\r\n"
> > -> "\r\n"
> > reading 141 bytes...
> > -> "{"error":"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."}"
> > read 141 bytes
> > Conn keep-alive
> > [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
> > /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:70:in `print_error' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:30:in `request_url'
> > /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:36:in `request_path' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/register.rb:61:in `run'
> > /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run' /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
> > /Users/Jignesh/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>' /Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `load'
> > /Users/Jignesh/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `
> > '
> 
> same here.

Hello, is this error resolved? Hope to inform the solution

**Comment by huahuaworld** [comment]
-> Pod installation complete! There is 1 dependency from the Podfile and 5 total pods installed.
   Building with `xcodebuild`. 
   Testing with `xcodebuild`. 
 -> NECopyrightedMedia (1.3.0)
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.11.3\r\nAuthorization: Token 06aba5daaea8592ad9087e904b642d5e\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 695\r\n\r\n"
<- "{\"name\":\"NECopyrightedMedia\",\"version\":\"1.3.0\",\"summary\":\"NECopyrightedMedia Kit\",\"homepage\":\"https://netease.im\",\"license\":{\"type\":\"Copyright\",\"text\":\" Copyright 2022 Netease \"},\"authors\":\"yunxin engineering department\",\"source\":{\"http\":\"https://yx-web-nosdn.netease.im/package/1664519588248/NECopyrightedMedia_iOS_v1.3.0.framework.zip?download=NECopyrightedMedia_iOS_v1.3.0.framework.zip\"},\"platforms\":{\"ios\":\"10.0\"},\"vendored_frameworks\":\"NECopyrightedMedia.framework\",\"dependencies\":{\"YYModel\":[],\"YXAlog_iOS\":[],\"BlocksKit\":[],\"libextobjc\":[]},\"frameworks\":\"Accelerate\",\"pod_target_xcconfig\":{\"VALID_ARCHS\":\"x86_64 armv7 arm64\"},\"user_target_xcconfig\":{\"VALID_ARCHS\":\"x86_64 armv7 arm64\"}}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Sat, 08 Oct 2022 01:34:59 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

same here
