### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by loicgriffie** [CocoaPods/cocoapods-trunk#116]
Looks like my email has been black listed on your side. When doing pod trunk register contact@hubkit.io i do not receive email to validate. But when sending email to the same address myself I receive it.

Regards

**Comment by loicgriffie** [comment]
Sorry guys, but i'm a bit of stuck here and we need to push a new version for our main client's app.

**Comment by orta** [comment]
We got a bounce from the mail-server that the email didn't exist back on the 7th, so I've removed it and it should come through 👍

**Comment by loicgriffie** [comment]
thanks a lot. It works 👏
