### ISSUE TITLE
Improper pod ownership resolution

### ISSUE THREAD

**Issue by youknowone** [CocoaPods/cocoapods-trunk#124]
I tried to upload a pod named `UIKitExtension`, but it shows  errors with other user's email.

By accessing `https://cocoapods.org/pods/UIKitExtension`, it redirects to my project.

But when I try to 
```
pod trunk push UIKitExtension.podspec
```

it shows error like:

```
Updating spec repo `master`
Validating podspec
 -> UIKitExtension (2.0.0)
    - NOTE  | [UIKitExtension/UIKitExtension] xcodebuild:  note: Using new build system
    - NOTE  | [UIKitExtension/UIKitExtension] xcodebuild:  note: Planning build
    - NOTE  | [UIKitExtension/UIKitExtension] xcodebuild:  note: Constructing build description
    - NOTE  | [UIKitExtension/UIKitExtension] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

[!] You (__@youknowone.org) are not allowed to push new versions for this pod. The owners of this pod are __@asnet.com.vn.
```

which is not my email address. 

I also tried to claiming my pod at https://trunk.cocoapods.org/claims/new, but I didn't get any response for a few months.

Any help?

**Comment by segiddins** [comment]
We got your claim and had marked it as resolved internally.

**Comment by orta** [comment]
Hi, yeah, sorry it looked like a set of claims we'd had around that time that were people claiming to own their own Pods and so I dismissed it - I'll assign it to your email.
