### ISSUE TITLE
Claim turnaround time?

### ISSUE THREAD

**Issue by chansen22** [CocoaPods/cocoapods-trunk#129]
I submitted a claim a little while ago, but I haven't heard anything about it since then. Is there an average time for resolving these requests? Should we receive an email verifying that our claim has been received?

Sorry if this is the wrong spot for this, but it seems like this process could use a little light.

Specifically it was for https://github.com/instacart/nantes

**Comment by orta** [comment]
Yeah, it's kinda blocked on my free time which I have very little of atm. Will take a look now.

**Comment by chansen22** [comment]
Thanks for jumping on it. Flappy Royale seems like a fun project ;)

**Comment by orta** [comment]
Alright - ran through the open disputes, thanks @chansen22 !
