### ISSUE TITLE
I have no access to my older email due to company changing email addresses

### ISSUE THREAD

**Issue by ohernandezIBM** [CocoaPods/cocoapods-trunk#149]
I noticed that I could not see new pod I deployed. I then used:

ohernandezltkmacs-MacBook-Pro:1.0.0 ohernandez@us.ibm.com$ pod trunk me

Name: Omar Hernandez
Email: ohernandez@us.ibm.com
Since: March 30th, 2018 14:30
Pods:
EOCore
EOCoreDebug
IBMTealeaf
IBMTealeafDebug
DigitalAnalytics
DigitalAnalyticsDebug
IBMTealeafReactNativeDebug
IBMTealeafReactNative
TealeafMD5
TealeafSHA2
Sessions:
March 30th, 2018 14:30 - August 5th, 2018 14:30. IP: 98.248.18.4 Description: IBM Customer Analytics Core Library
June 1st, 2018 16:17 - August 28th, 18:55. IP: 67.180.26.237
I forgot to update my email, I tried #5109. I registered a new email:

ohernandezltkmacs-MacBook-Pro:1.0.0 ohernandez@us.ibm.com$ pod trunk me

Name: Omar Hernandez
Email: omar.hernandez@acoustic.co
Since: April 22nd, 19:10
Pods: None
Sessions:
April 22nd, 19:10 - August 28th, 19:20. IP: 67.164.73.137
But now I can not add new owners on my old repos. How can I fix this?

I then did :
ohernandezltkmacs-MacBook-Pro:1.0.0 ohernandez@us.ibm.com$ pod trunk register ohernandez@us.ibm.com 'Omar Hernandez'
[!] Please verify the session by clicking the link in the verification email that has been sent to ohernandez@us.ibm.com

But I can not verify my email. I need help adding me to the following:
https://cocoapods.org/owners/30201

**Comment by ohernandezIBM** [comment]
Is there a way to edit my profile with new email?

**Comment by amorde** [comment]
Solved - see https://github.com/CocoaPods/CocoaPods/issues/9743
