### ISSUE TITLE
Cannot receive email for pod trunk register - DJI SDK

### ISSUE THREAD

**Issue by dji-dev** [CocoaPods/cocoapods-trunk#150]
Hi @orta @alloy @kylef @paulb777 , the cocoapods trunk authentication token on my MacBook Pro is invalid now and I try to renew it by running "pod trunk register" using terminal. But cannot receive email after trying several times. We change to different email, still not work. 

Here are our existing pods info:

  - Name:     DJI SDK
  - Email:    sdk@dji.com
  - Since:    March 29th, 2016 03:27
  - Pods:
    - DJI-SDK-iOS
    - DJI-UILibrary-iOS
    - DJI-UXSDK-iOS
    - DJIWidget
    - DJINetworkRTKHelper
    - DJI-UXSDK-iOS-Beta-Communication
    - DJI-UXSDK-iOS-Beta-Core
    - DJI-UXSDK-iOS-Beta-Widgets
    - DJI-UXSDK-iOS-Beta
    - DJIFlySafeDatabaseResource

We assume our email address: **@dji.com** is on the spam blacklist of CocoaPods trunk service? Could you help to resolve this issue, we are trying to upload a new version of DJI Mobile SDK. Any help is appreciated, thanks!

**Comment by dnkoutso** [comment]
@amorde @dji-dev was this resolved?

**Comment by amorde** [comment]
Not that I am aware of

**Comment by orta** [comment]
They emailed me privately and I looked at it, their mail server was blocking the service we use to send emails - it's resolved 👍
