### ISSUE TITLE
'pod trunk register ' The verification code cannot be received by the mailbox

### ISSUE THREAD

**Issue by CCSH** [CocoaPods/cocoapods-trunk#154]
Hey team, thanks for your work.

I don't receive any email from pod trunk register 624089195@qq.com 'CCSH'. Am I in a blacklist or anything?

**Comment by rrolland** [comment]
Hello,

Same issue for me today for an outlook mailbox.

**Comment by ajman83** [comment]
Exactly Same Issue, Doesn't Arrive and Continuously Responsive

**Comment by gutoglup** [comment]
Same problem here too
