### ISSUE TITLE
Unable to interpret the specified path

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/cocoapods-trunk#54]
I am getting this error message and have no idea what it means:
https://github.com/CocoaPods/cocoapods-trunk/blob/7596a6a39f2a122c33c23614b062bf36d062be88/lib/pod/command/trunk/push.rb#L93-L95

Here is my podspec that used to work fine but now triggers that error:
https://github.com/fulldecent/FDSoundActivatedRecorder/blob/4ca524559999eca411a382b8293521fcfd19e257/FDSoundActivatedRecorder.podspec

**Comment by segiddins** [comment]
What's the output of `pod env` and the contents of the podspec?

**Comment by segiddins** [comment]
Closing due to lack of response.
