### ISSUE TITLE
[!] You are not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by renebigot** [CocoaPods/cocoapods-trunk#56]
Hello,
I've created a lib on github some time ago. Someone helped me to make this library compatible with Cocoapods.
The problem is that he's created the pod, so I can't update it.
Is there a way to become the pod owner (as I'm the repo owner) ?

The Pod can be find here : https://cocoapods.org/pods/XlsxReaderWriter

You'll see in the pod description that I'm really the repo owner.

Should I fix it with https://trunk.cocoapods.org/claims/new ?

**Comment by renebigot** [comment]
I've claim ownership thanks to the link below. Thank you.

**Comment by orta** [comment]
Ah yeah, sorry, missed this, claims was the right way to go :+1:

**Comment by renebigot** [comment]
no worry. :)
