### ISSUE TITLE
More engaging message when pod is successfully pushed

### ISSUE THREAD

**Issue by icanzilb** [CocoaPods/cocoapods-trunk#73]
As per: https://twitter.com/orta/status/786828976559951872?lang=en

Tweets with an image are enjoying much higher % of engagements - I've seen often people announce they pushed up a new version of their pod and attach a screenshot like this one:

![image](https://cloud.githubusercontent.com/assets/633862/19379018/384474b8-91f0-11e6-9fea-31ba1eb50c74.png)

As proposed to @orta - a nicer looking message will make for nicer screenshots and eventually more updates of the owner's pod, and ultimately better software (😜 @neonichu )

Fav emojis for shipped new pod version? 🎉🚢🚀🐷🔔?

I'm gonna try to send a PR this weekend, but if you have ideas - jot them below in the comments 👇

**Comment by DanToml** [comment]
could do something like:
🚀 You just released TaskQueue 1.0.1!
📝 http://cocoapods.org/pods/TaskQueue

**Comment by icanzilb** [comment]
I'd also have another line with the date - makes for nicer screenshots when sharing, so people know the content is fresh: 

📅 October 14th, 2016

**Comment by icanzilb** [comment]
🎉 Congrats!

🚀 TaskQueue 1.0.1 is up
📅 October 14th, 2016
📝 http://cocoapods.org/pods/TaskQueue
👍 Tell your friends

**Comment by orta** [comment]
👍

**Comment by icanzilb** [comment]
Opened a PR: https://github.com/CocoaPods/cocoapods-trunk/pull/76
