### ISSUE TITLE
How to reset my Name?

### ISSUE THREAD

**Issue by iTofu** [CocoaPods/cocoapods-trunk#82]
If I run `pod trunk register devtip@163.com 'ErrorName'`, after how to reset name?

**Comment by iTofu** [comment]
https://github.com/CocoaPods/CocoaPods/issues/6182

**Comment by orta** [comment]
Looks like this is a dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/155 - you're welcome to take a stab at fixing it 👍
