### ISSUE TITLE
Publish new pod issue

### ISSUE THREAD

**Issue by mmdumi** [CocoaPods/cocoapods-trunk#88]
I'm trying to push the following repo as a new pod `https://github.com/what3words/w3w-swift-wrapper` but pod trunk push gives me the following error:

> [!] You (mihai@wearewip.com) are not allowed to push new versions for this pod. The owners of this pod are shobithalva@gmail.com.

I've checked and there is no other existing pod with this name, and I'm not sure from where the second email address is fetched.

**Comment by orta** [comment]
This is likely a pod that was created and deleted, have you emailed the previous owner?

**Comment by orta** [comment]
They got access to this pod in https://github.com/CocoaPods/trunk.cocoapods.org/issues/259
