### ISSUE TITLE
cocoapods-trunk only dependency `netrc` 0.7.8

### ISSUE THREAD

**Issue by FfanPublic** [CocoaPods/cocoapods-trunk#89]
cocoapods-trunk has the dependency `netrc`, but its version is `=0.7.8`. I think it is very hard to work with other gem. eg. `fir-cli`:
```
    cocoapods (= 1.2.0) was resolved to 1.2.0, which depends on
      cocoapods-trunk (< 2.0, >= 1.1.2) was resolved to 1.1.2, which depends on
        netrc (= 0.7.8)

    fir-cli (= 1.5.1) was resolved to 1.5.1, which depends on
      rest-client (~> 2.0) was resolved to 2.0.1, which depends on
        netrc (~> 0.8)
```

could CP upgrade the netrc version?

**Comment by orta** [comment]
Sure, can't see why not, want to look at that?

**Comment by orta** [comment]
Maybe see if you can get https://github.com/CocoaPods/cocoapods-trunk/pull/84 mergeable?

**Comment by Whirlwind** [comment]
Is there a plant to merge #84 ?

**Comment by segiddins** [comment]
Once the comments on it are addressed

**Comment by pronebird** [comment]
Same issue here. Cannot use `cocoapods` with `rest-client`.

**Comment by Whirlwind** [comment]
:( I just use `rest-client`, and I get this issue again.

**Comment by dvlprliu** [comment]
I get the same issue, maybe get this PR #95 merged?

**Comment by DanToml** [comment]
0.11 is now out in cocoapods-trunk 1.3.0
