### ISSUE TITLE
How can I modify the email address registered for several pods?

### ISSUE THREAD

**Issue by WelkinXie** [CocoaPods/cocoapods-trunk#90]
I am working with a new mac so I have to register again, but I can not receive the verification email (welkin995@126.com). I have checked the spam but there is nothing. Thus I want to modify the email address. I have submitted a claim via trunk.cocoapods.org but receive no response. What should I do next?

**Comment by orta** [comment]
Can you give me a list of the Pods? I've changed WXWaveView so far to use your `qq.com` email

**Comment by WelkinXie** [comment]
I've sent you an email about the Pods. Thanks!

**Comment by orta** [comment]
This dispute is now resolved.
