### ISSUE TITLE
Not getting session email.

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/cocoapods-trunk#98]
Hey! I cannot receive a session with the email daniel@graphkit.io. Thank you!

**Comment by danieldahan** [comment]
Hey :) Any update to this, I need to make a release. Thank you!

**Comment by orta** [comment]
Both of your emails came back as bounced from your mail host, and were marked for not being sent to. I've removed the mark, so the next email won't be suppressed from our side 👍 

<img width="1424" alt="screen shot 2017-09-17 at 8 57 12 am" src="https://user-images.githubusercontent.com/49038/30521021-52a69fd4-9b86-11e7-9693-5d5f84ea0e7c.png">

**Comment by danieldahan** [comment]
Thank you!

**Comment by danieldahan** [comment]
Thank you! :)
